GitEDU/GitEDU/urls.py
from django.conf.urls import url, include
from django.contrib import admin

#from ideApp import urls as ide_urls
import ideApp.urls
import authApp.urls
import socialApp.urls

import django_app_lti.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include(authApp.urls, namespace="auth")),
    url(r'^lti/', include(django_app_lti.urls, namespace="lti")),
    url(r'^ide/', include(ideApp.urls, namespace="ide")),
    url(r'^social/', include(socialApp.urls, namespace="social"))
]

GitEDU/ideApp/urls.py
from django.conf.urls import url

from . import views

appname = "ideApp"
urlpatterns = [
    url(r'^(?P<class_id>[0-9]*)/$', views.EditorClassView.as_view(), name="class"),
    url(r'^(?P<class_id>[0-9]*)/(?P<assignment_id>[0-9]*)$', views.EditorAssignmentView.as_view(), name="assignment"),
    url(r'^ns/(?P<namespace>[a-zA-Z0-9]*)/$', views.NamespaceView.as_view(), name="namespace"),
    url(r'^new/namespace/$', views.NewNamespaceView.as_view(), name="new_namespace"),
    url(r'^new/repository/$', views.NewFullRepositoryView.as_view(), name="new_full_repository"),
    url(r'^new/repo_file/$', views.NewRepositoryFileFormView.as_view(), name="new_repo_file"),
    url(r'^repo/(?P<namespace>[a-zA-Z0-9]*)/(?P<repository>[a-zA-Z0-9]*)/', views.RepositoryView.as_view(),
        name="repository"),
    url(r'^rf/(?P<namespace>[a-zA-Z0-9]*)/(?P<repository>[a-zA-Z0-9]*)/(?P<file_path>[a-zA-Z0-9/]*\.[a-zA-Z0-9]*)$',
        views.EditorFileView.as_view(), name="file_editor"),
    url(r'^cf/(?P<namespace>[a-zA-Z0-9]*)/(?P<repository>[a-zA-Z0-9]*)/(?P<change>[a-z0-9]*)/(?P<file_path>[a-zA-Z0-9/]*\.[a-zA-Z0-9]*)$',
        views.EditorChangeFileView.as_view(), name="change_file_editor"),
    url(r'^checkout/(?P<namespace>[a-zA-Z0-9]*)/(?P<repository>[a-zA-Z0-9]*)/(?P<change>[a-z0-9]*)/$',
        views.CheckoutFileVersionView.as_view(), name="checkout"),
    url(r'execute/(?P<namespace>[a-zA-Z0-9]*)/(?P<repository>[a-zA-Z0-9]*)/', views.RepositoryExecutionView.as_view(),
        name='repository_execution'),
    url(r'execute/status/(?P<job_id>[a-zA-Z0-9-]*)/', views.ExecutionStatusView.as_view(), name='execution_status'),
    url(r'execute/result/(?P<job_id>[a-zA-Z0-9-]*)/', views.ExecutionResultView.as_view(), name='execution_result')
]

GitEDU/socialApp/urls.py
from django.conf.urls import url

from . import views

appname = "socialApp"
urlpatterns = [
    url(r'^user/(?P<user>[a-zA-Z0-9]*)/$', views.UserView.as_view(), name="user"),
]

GitEDU/templates/editor/full_repository_form.html
{% extends 'form.html' %}

{% block form_target %}{% url 'ide:new_full_repository' %}{% endblock %}

{% block form_additional_def %}target="_blank"{% endblock %}

{% comment %}
{% block form_submit_button_classes %}btn btn-success btn-lg{% endblock %}
{% endcomment %}

GitEDU/templates/editor/full_repository_form_page.html
{% extends 'form_page.html' %}

{% block title %}Formulario - Repositorio{% endblock %}

{% block page_title %}Formulario: Repositorio{% endblock %}

{% block form_target %}{% url 'ide:new_full_repository' %}{% endblock %}

{% block form_additional_def %}target="_blank"{% endblock %}

GitEDU/templates/editor/namespace.html
{% extends 'base.new.html' %}

{% block title %}Namespace - {{ namespace.namespace }}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">{{ namespace.namespace }}</li>
{% endblock %}

{% block content %}
    <section class="namespace">
        <div class="container-fluid">
            <header>
                <h1 class="h3 display">
                    Contenidos del Namespace {{ namespace.namespace }}
                </h1>
            </header>
            {% comment %}
                {% if detalles %}
                    <p><em>Dueno:</em> {{ user.first_name }}</p>
                    <p><em>Apellidos:</em> {{ user.last_name }}</p>
                    <p><em>Correo Electronico:</em> {{ user.email }}</p>
                    <p><a class="btn-outline" href="{% url 'new-code' user.username %}">Crear nuevo archivo de
                        codigo</a></p>
                {% endif %}
                {% if tiene_codigo %}
                    <h3 class="titulos">Es dueño de(los) codigo(s):</h3>

                    {% for code in mycode %}
                        <p><a class="cod-lista" href="/code/{{ code.code_id }}/">{{ code.language }}
                            - {{ code.file_name }}</a></p>


                    {% endfor %}

                {% endif %}
                {% if esCollab %}
                    <h3>Colabora en:</h3>
                    <ul class="navbar-fixed-top">
                        {% for collab_code in collab_codes %}
                            <li><a href="/code/{{ collab_code.code_id }}/">{{ collab_code.language }}
                                - {{ collab_code.file_name }}</a>
                                - por <a href="{% url 'user-profile' collab_code.user_owner.username %}">
                                    {{ collab_code.user_owner.username }}</a></li>
                        {% endfor %}
                    </ul>
                {% endif %}
            {% endcomment %}
            <hr>
            <header>
                <h3 class="h3 display">Repositorios:</h3>
            </header>
            <div class="row">
                {% for repository in repositories %}
                    <div class="col-lg-3">
                        <div class="card">
                            <div class="card-body">
                                <p>
                                    {{ repository.namespace.namespace }} /
                                    <a href="{% url 'ide:repository' namespace=repository.namespace.namespace repository=repository.repository %}">
                                        {{ repository.repository }}
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <hr>
            <header>
                <h3 class="h3 display">Usuarios Activos:</h3>
            </header>
            <div class="row">
                {% for user in users %}
                    <div class="col-lg-3">
                    <div class="card">
                        <div class="card-body">
                        <p>
                            {% if user == 'Anonymous' %}
                                {{ user }}
                            {% else %}
                                <a href="{% url 'social:user' user %}">{{ user }}</a>
                            {% endif %}
                        </p>
                        </div>
                    </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

GitEDU/templates/editor/namespace_form.html
{% extends 'form.html' %}

{% block form_target %}{% url 'ide:new_namespace' %}{% endblock %}

{% block form_additional_def %}target="_blank"{% endblock %}

{% comment %}
{% block form_submit_button_classes %}btn btn-success btn-lg{% endblock %}
{% endcomment %}

GitEDU/templates/editor/namespace_form_page.html
{% extends 'form_page.html' %}

{% block title %}Formulario - Namespace{% endblock %}

{% block page_title %}Formulario: Namespace{% endblock %}

{% block form_target %}{% url 'ide:new_namespace' %}{% endblock %}

{% block form_additional_def %}target="_blank"{% endblock %}

GitEDU/templates/editor/new_repository_file_form.html
{% extends 'form.html' %}

{% block form_target %}{% url 'ide:new_repo_file' %}{% endblock %}

{% block form_additional_def %}target="_blank"{% endblock %}

{% block form_submit_text %}Crear Archivo{% endblock %}

{% comment %}
{% block form_submit_button_classes %}btn btn-success btn-lg{% endblock %}
{% endcomment %}

GitEDU/templates/editor/new_repository_file_form_page.html
{% extends 'form_page.html' %}

{% block title %}Formulario - Nuevo Repositorio Archivo{% endblock %}

{% block page_title %}Formulario: Nuevo Repositorio Archivo{% endblock %}

{% block form_target %}{% url 'ide:new_repo_file' %}{% endblock %}

{% block form_additional_def %}target="_blank"{% endblock %}

GitEDU/templates/editor/repository.html
{% extends 'base.new.html' %}

{% block title %}Repositorio - {{ namespace }} / {{ repository }}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'ide:namespace' namespace=namespace %}">{{ namespace }}</a></li>
    <li class="breadcrumb-item active">{{ repository }}</li>
{% endblock %}

{% block content %}
    <section class="repository">
        <div class="container-fluid">
            <header>
                <h1 class="h3 display">Contenidos del Repositorio {{ namespace }} / {{ repository }}</h1>
            </header>
            <hr>
            {% if detalles %}
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <p><em>Dueño:</em> <a
                                        href="{% url 'social:user' owner.user.username %}">{{ owner.user.username }}</a>
                                </p>
                                <p><em>Grupo:</em> {{ group }}</p>
                                <p><em>Namespace:</em> <a
                                        href="{% url 'ide:namespace' namespace=namespace %}">{{ namespace }}</a></p>
                                {% comment %}
                                    <p><a class="btn-outline" href="{% url 'new-code' user.username %}">Crear nuevo
                                        archivo de codigo</a></p>{% endcomment %}
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
            {% endif %}
            <header>
                <h3 class="h3 display">Archivos:</h3>
            </header>
            <div class="row">
                {% for file in files %}
                    <div class="col-lg-3">
                        <div class="card">
                            <div class="card-body">
                                <p>
                                    <a href="{% url 'ide:file_editor' namespace=namespace repository=repository file_path=file %}">
                                        {{ file }}
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <hr>
            {% if detalles %}
                <div class="row">
                    <div class="col-lg-12">
                        {% include 'editor/new_repository_file_form.html' with form=new_file_form form_title="Nuevo Archivo:" only %}
                    </div>
                </div>
                <hr>
            {% endif %}
            <header>
                <h3 class="h3 display">Usuarios Activos:</h3>
            </header>
            <div class="row">
                {% for user in users %}
                    <div class="col-lg-3">
                        <div class="card">
                            <div class="card-body">
                                <p>
                                    {% if user == 'Anonymous' %}
                                        {{ user }}
                                    {% else %}
                                        <a href="{% url 'social:user' user %}">{{ user }}</a>
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}